version: '2'
services: 
  web:
      build: .
      #working_dir: /go/src
      ports:
      - "8080:8080"
      links:
      - redis
      environment:
        - REDIS_URL=redis://redis:6379

      stdin_open: true # docker run -i
      tty: true 
  redis:
      image: redis
      # ports:
      # - ":6379"
